import PropTypes from "prop-types";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import "../globals.scss";
import { decrypt } from "../lib/session";
import { SessionProvider } from "../context/sessionProvider";
import { ToastProvider } from "../context/toastProvider";
import PageWrapper from "./components/PageWrapper";
import { getDictionaries } from "./dictionaries";
import { hasLocale } from "@/utils/urls";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  const { lang } = await params;

  if (!hasLocale(lang)) {
    notFound();
  }

  const cookieStore = await cookies();
  const sessionCookie = cookieStore.get("session")?.value;
  const userId = cookieStore.get("userId")?.value || null;
  let permissions = [];

  if (sessionCookie) {
    try {
      const payload = await decrypt(sessionCookie);
      permissions = payload.permissions || [];
    } catch (error) {
      console.error("Error decoding session:", error.message);
    }
  }

  const dictionaries = await getDictionaries(lang, ["navbar", "backoffice"]);

  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ToastProvider>
          <SessionProvider permissions={permissions} userId={userId}>
            <PageWrapper
              backofficeDictionary={dictionaries.backoffice}
              navbarDictionary={dictionaries.navbar}
            >
              {children}
            </PageWrapper>
          </SessionProvider>
        </ToastProvider>
      </body>
    </html>
  );
}

LocaleLayout.propTypes = {
  children: PropTypes.node.isRequired,
  params: PropTypes.object.isRequired,
};
