import PropTypes from "prop-types";
import localFont from "next/font/local";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import "../globals.scss";
import { getCurrentSession } from "../lib/session";
import { SessionProvider } from "../context/sessionProvider";
import { ToastProvider } from "../context/toastProvider";
import PageWrapper from "./components/PageWrapper";
import ErrorBoundary from "./components/ErrorBoundary";
import { hasLocale } from "@/utils/urls";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  const { lang } = await params;

  if (!hasLocale(lang)) {
    notFound();
  }

  setRequestLocale(lang);

  const session = await getCurrentSession();
  const userId = session?.userId || null;
  const permissions = session?.permissions || [];

  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextIntlClientProvider>
          <ErrorBoundary>
            <ToastProvider>
              <SessionProvider permissions={permissions} userId={userId}>
                <PageWrapper>{children}</PageWrapper>
              </SessionProvider>
            </ToastProvider>
          </ErrorBoundary>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

LocaleLayout.propTypes = {
  children: PropTypes.node.isRequired,
  params: PropTypes.object.isRequired,
};
