import PropTypes from "prop-types";
import localFont from "next/font/local";
import { Navbar } from "./components/Navbar";
import "./globals.scss";
import { UserProvider } from "context/UserContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider>
          <header>
            <Navbar />
          </header>
          {children}
          <footer>
            Gabriel Colom
          </footer>
        </UserProvider>

      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node, // Validamos que 'children' pueda ser cualquier tipo de nodo de React
};
