import PropTypes from "prop-types";
import localFont from "next/font/local";
import { Navbar } from "./components/Navbar";
import { cookies } from "next/headers";
import "./globals.scss";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const parsedCookies = cookieStore.getAll().reduce((acc, { name, value }) => {
    acc[name] = value;
    return acc;
  }, {});

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <Navbar cookies={parsedCookies} />
        </header>
        {children}
        <footer>
          Gabriel Colom
        </footer>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node,
};
