import PropTypes from "prop-types";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import "./globals.scss";
import { decrypt } from "./lib/session";
import { SessionProvider } from "./context/sessionProvider";
import { ToastProvider } from "./context/toastProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const sessionCookie = cookieStore.get("session")?.value;
  const userId = cookieStore.get("userId")?.value || null;
  let permissions = [];

  if (sessionCookie) {
    try {
      const payload = await decrypt(sessionCookie);
      permissions = payload.permissions || [];
    } catch (error) {
      console.error("Error decoding session:", error.message);
    }
  }

  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ToastProvider>
          <SessionProvider permissions={permissions} userId={userId}>
            {children}
          </SessionProvider>
        </ToastProvider>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node,
};
